<!DOCTYPE html>
<html>
    <head>
        <?php echo $this->getChildHtml('head'); ?>
    </head>
    <body>
        <?php echo $this->getChildHtml('after_body_start'); ?>
        <?php echo $this->getChildHtml('header'); ?>
        <div class="content">
            <?php echo $this->getChildHtml('content'); ?>
        </div>
        <?php echo $this->getChildHtml('footer'); ?>
        <?php echo $this->getChildHtml('before_body_end'); ?>
    </body>
</html>